"""initial_schema

Revision ID: 641438be3ff8
Revises: 
Create Date: 2026-04-21 00:21:46.905730

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '641438be3ff8'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('matches',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('match_id', sa.String(length=20), nullable=False),
    sa.Column('home_team', sa.String(length=100), nullable=False),
    sa.Column('away_team', sa.String(length=100), nullable=False),
    sa.Column('league_code', sa.String(length=50), nullable=True),
    sa.Column('league_name', sa.String(length=100), nullable=True),
    sa.Column('kickoff_time', sa.DateTime(timezone=True), nullable=True),
    sa.Column('season', sa.String(length=10), nullable=True),
    sa.Column('analyzed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('ht_scores_1', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('ht_scores_x', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('ht_scores_2', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('ht_all_ratios', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('h2_scores_1', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('h2_scores_x', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('h2_scores_2', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('h2_all_ratios', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('ft_scores_1', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('ft_scores_x', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('ft_scores_2', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('ft_all_ratios', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('actual_ht_home', sa.Integer(), nullable=True),
    sa.Column('actual_ht_away', sa.Integer(), nullable=True),
    sa.Column('actual_ft_home', sa.Integer(), nullable=True),
    sa.Column('actual_ft_away', sa.Integer(), nullable=True),
    sa.Column('result_fetched_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('match_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('matches')
    # ### end Alembic commands ###
