"""add_h2_scores_and_kickoff_time

Revision ID: c1b1b4cd333b
Revises: 641438be3ff8
Create Date: 2026-04-21 20:06:53.271766

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c1b1b4cd333b'
down_revision: Union[str, None] = '641438be3ff8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('matches', sa.Column('actual_h2_home', sa.Integer(), nullable=True))
    op.add_column('matches', sa.Column('actual_h2_away', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('matches', 'actual_h2_away')
    op.drop_column('matches', 'actual_h2_home')
    # ### end Alembic commands ###
