import type { PatternResult } from "@/lib/types";
import type { Pick } from "@/lib/confidence";
import type { CartItem } from "@/lib/cart";

export function makePatternResult(overrides: Partial<PatternResult> = {}): PatternResult {
  return {
    match_count: 0,
    result_1_pct: 0,
    result_x_pct: 0,
    result_2_pct: 0,
    dc_1x_pct: 0,
    dc_x2_pct: 0,
    dc_12_pct: 0,
    alt_15_pct: 0,
    ust_15_pct: 0,
    alt_25_pct: 0,
    ust_25_pct: 0,
    alt_35_pct: 0,
    ust_35_pct: 0,
    kg_var_pct: 0,
    kg_yok_pct: 0,
    hnd_h20_1_pct: 0,
    hnd_h20_x_pct: 0,
    hnd_h20_2_pct: 0,
    hnd_h10_1_pct: 0,
    hnd_h10_x_pct: 0,
    hnd_h10_2_pct: 0,
    hnd_a10_1_pct: 0,
    hnd_a10_x_pct: 0,
    hnd_a10_2_pct: 0,
    hnd_a20_1_pct: 0,
    hnd_a20_x_pct: 0,
    hnd_a20_2_pct: 0,
    ms1_alt15_pct: 0,
    ms1_ust15_pct: 0,
    msx_alt15_pct: 0,
    msx_ust15_pct: 0,
    ms2_alt15_pct: 0,
    ms2_ust15_pct: 0,
    ms1_alt25_pct: 0,
    ms1_ust25_pct: 0,
    msx_alt25_pct: 0,
    msx_ust25_pct: 0,
    ms2_alt25_pct: 0,
    ms2_ust25_pct: 0,
    ms1_kg_var_pct: 0,
    ms1_kg_yok_pct: 0,
    msx_kg_var_pct: 0,
    msx_kg_yok_pct: 0,
    ms2_kg_var_pct: 0,
    ms2_kg_yok_pct: 0,
    fark_ev1_pct: 0,
    fark_ev2_pct: 0,
    fark_ev3p_pct: 0,
    fark_ber_pct: 0,
    fark_dep1_pct: 0,
    fark_dep2_pct: 0,
    fark_dep3p_pct: 0,
    ev_alt_05_pct: 0,
    ev_ust_05_pct: 0,
    ev_alt_15_pct: 0,
    ev_ust_15_pct: 0,
    ev_alt_25_pct: 0,
    ev_ust_25_pct: 0,
    dep_alt_05_pct: 0,
    dep_ust_05_pct: 0,
    dep_alt_15_pct: 0,
    dep_ust_15_pct: 0,
    dep_alt_25_pct: 0,
    dep_ust_25_pct: 0,
    ev_ht_alt_05_pct: 0,
    ev_ht_ust_05_pct: 0,
    dep_ht_alt_05_pct: 0,
    dep_ht_ust_05_pct: 0,
    gol_01_pct: 0,
    gol_23_pct: 0,
    gol_45_pct: 0,
    gol_6p_pct: 0,
    encok_gol_1y_pct: 0,
    encok_gol_esit_pct: 0,
    encok_gol_2y_pct: 0,
    iy_alt_05_pct: 0,
    iy_ust_05_pct: 0,
    iy_alt_15_pct: 0,
    iy_ust_15_pct: 0,
    iy_alt_25_pct: 0,
    iy_ust_25_pct: 0,
    iki_yari_alt15_pct: 0,
    iki_yari_ust15_pct: 0,
    h2_kg_var_pct: 0,
    h2_kg_yok_pct: 0,
    iy_h2_kg_vv_pct: 0,
    iy_h2_kg_vy_pct: 0,
    iy_h2_kg_yv_pct: 0,
    iy_h2_kg_yy_pct: 0,
    ev_iki_yari_gol_pct: 0,
    dep_iki_yari_gol_pct: 0,
    ev_encok_1y_pct: 0,
    ev_encok_esit_pct: 0,
    ev_encok_2y_pct: 0,
    dep_encok_1y_pct: 0,
    dep_encok_esit_pct: 0,
    dep_encok_2y_pct: 0,
    iy_ms_11_pct: 0,
    iy_ms_1x_pct: 0,
    iy_ms_12_pct: 0,
    iy_ms_x1_pct: 0,
    iy_ms_xx_pct: 0,
    iy_ms_x2_pct: 0,
    iy_ms_21_pct: 0,
    iy_ms_2x_pct: 0,
    iy_ms_22_pct: 0,
    score_freq: {},
    ht_result_1_pct: 0,
    ht_result_x_pct: 0,
    ht_result_2_pct: 0,
    ht_dc_1x_pct: 0,
    ht_dc_x2_pct: 0,
    ht_dc_12_pct: 0,
    ht_alt_15_pct: 0,
    ht_ust_15_pct: 0,
    ht_kg_var_pct: 0,
    ht_kg_yok_pct: 0,
    h2_result_1_pct: 0,
    h2_result_x_pct: 0,
    h2_result_2_pct: 0,
    ...overrides,
  };
}

export function makePick(overrides: Partial<Pick> = {}): Pick {
  return {
    marketKey: "result",
    field: "result_1_pct",
    marketLabel: "Maç Sonucu",
    selectionLabel: "1",
    pct: 70,
    pctA: 70,
    pctB: null,
    matchCountA: 20,
    matchCountB: 0,
    marketWeight: 1.0,
    archive: "A",
    confidence: 0.65,
    ...overrides,
  };
}

export function makeCartItem(overrides: Partial<CartItem> = {}): CartItem {
  return {
    matchId: "2813084",
    homeTeam: "Kayserispor",
    awayTeam: "Karagumruk",
    marketKey: "result",
    selectionLabel: "1",
    marketLabel: "Maç Sonucu",
    pct: 70,
    archive: "A",
    period: "ft",
    addedAt: 1700000000000,
    ...overrides,
  };
}
